apiVersion: networking.k8s.io/v1
# https://kubernetes.io/docs/concepts/services-networking/network-policies
kind: NetworkPolicy
metadata:
  name: {{ include "postgres.fullname" . }}
spec:
  podSelector:
    matchLabels: {{- include "postgres.selectorLabels" . | nindent 6 }}
  policyTypes: [Ingress, Egress]
  egress: []
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: buch
              app.kubernetes.io/name: buch
              app.kubernetes.io/instance: buch
      ports:
        - port: {{ .Chart.Name }}
          protocol: TCP
    - from:
        - podSelector:
            matchLabels:
              {{- include "pgadmin.selectorLabels" . | nindent 14 }}
      ports:
        - port: {{ .Chart.Name }}
          protocol: TCP
