# Aufruf:   helmfile apply
#               zzgl. Port-Forwarding
#           helmfile destroy

releases:
  - name: videospiel
    namespace: acme
    chart: extras/videospiel
    values: [extras/videospiel/dev.yaml]
    #wait: true
