# Aufruf:   docker compose -f jenkins.yaml up
#           docker compose -f jenkins.yaml down
#           docker compose -f jenkins.yaml exec jenkins bash

---
# https://github.com/compose-spec/compose-spec/blob/master/spec.md#compose-file
# https://github.com/compose-spec/compose-spec/blob/master/spec.md#services-top-level-element
# https://docs.docker.com/compose/compose-file
# https://docs.docker.com/compose/compose-file/compose-file-v3
services:
  jenkins-certs:
    image: docker:22.06.0-beta.0-dind
    volumes:
      - type: bind
        source: C:/Zimmermann/volumes/jenkins/certs
        target: /certs/client
      - type: bind
        source: C:/Zimmermann/volumes/jenkins/data
        target: /var/jenkins_home
    privileged: true
    networks:
      jenkins:
        # alternative hostnames
        aliases: ['docker']
    environment:
      DOCKER_TLS_CERTDIR: /certs
      TZ: Europe/Berlin
    container_name: jenkins-cert
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
  jenkins:
    image: juergenzimmermann/jenkins:1.0.0
    ports:
      - published: 7070
        target: 8080
    depends_on: ['jenkins-certs']
    volumes:
      - type: bind
        source: C:/Zimmermann/volumes/jenkins/certs
        target: /certs/client
        read_only: true
      - type: bind
        source: C:/Zimmermann/volumes/jenkins/data
        target: /var/jenkins_home
    networks: ['jenkins']
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
      TZ: Europe/Berlin
    container_name: jenkins
    hostname: jenkins
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "2"
    #       memory: 4096M
networks:
  jenkins: {}
