# https://helm.sh/docs/chart_best_practices/values

nodeConfig: development
loglevel: debug
logPretty: "true"
logHealthyPretty: "true"
dbPassword: p
dbPopulate: "true"
userPasswordEncoded: "$argon2i$v=19$m=4096,t=3,p=1$aaxA2v/9rRSPGkwYN+NQog$27Huii1XtD3iEd62fog+04G26LRPZMHoYCI6AGKTL8M"

replicaCount: 1

resourcesRequests:
  #cpu: 1000m
  memory: 768Mi
  #memory: 1536Mi

resourcesLimits:
  #cpu: 2000m
  memory: 768Mi
  #memory: 1536Mi

livenessProbe:
  initialDelay: 45
  timeout: 15
  period: 120
  failureThreshold: 1
readinessProbe:
  initialDelay: 45
  timeout: 15
  period: 120
  failureThreshold: 1

autoscaling:
  enabled: false
