# Aufruf:   helmfile apply
#               zzgl. Port-Forwarding durch port-forward.ps1
#           helmfile destroy

releases:
  - name: mailserver
    namespace: acme
    chart: mailserver
    values: [mailserver/dev.yaml]
    wait: true
