# Aufruf:   i.a. bereits eingestellt:   $env:SKAFFOLD_PROFILE = 'dev'
#           skaffold dev
#           skaffold delete

apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: mailserver
deploy:
  helm:
    releases:
      - name: mailserver
        chartPath: mailserver
        valuesFiles: [mailserver/values.yaml]
        namespace: acme
profiles:
  - name: dev
    activation:
      - env: SKAFFOLD_PROFILE=dev
    deploy:
      helm:
        releases:
          - name: mailserver
            chartPath: mailserver
            valuesFiles: [mailserver/values.yaml, mailserver/dev.yaml]
            namespace: acme
    portForward:
      - resourceType: service
        resourceName: mailserver
        port: mailserver-http
        localPort: 5080
