// Preview durch <Strg><Shift>v

= Entwickler/innen/handbuch
:doctype: book
:toc: left
:sectanchors:
:sectlinks:
:sectnums:
:source-highlighter: coderay
:icons: font
// :kroki-server-url: https://kroki.io

// https://github.com/asciidoctor/asciidoctorj
// https://github.com/asciidoctor/asciidoctor-diagram
// http://de.plantuml.com/classes.html
// http://de.plantuml.com/component.html
// https://github.com/odrotbohm/asciidoctor-plantuml

== Der Applikationsserver

=== Der Applikationsserver im Überblick

Verschiedene Use Cases für Administratoren, Mitarbeiter und Kunden.          

.Use Cases
[plantuml,use-cases,svg]
----
include::use-cases.plantuml[]
----

Das Komponentendiagramm ist ein Strukturdiagramm. Es zeigt eine bestimmte Sicht 
auf die Struktur des modellierten Systems.

.Komponentendiagramm
[plantuml,komponenten,svg]
----
include::komponenten.plantuml[]
----

=== Die REST-Schnittstelle

GetController ist Teil der Präsentationsschicht. Nimmt Requests entgegen für Suchen.

."VideospielGetController" für Lesezugriffe an der REST-Schnittstelle
[plantuml,VideospielGetController,svg]
----
include::VideospielGetController.plantuml[]
----

Teil der Präsentationsschicht. Nimmt Requests entgegen für Schreiben.

."VideospielWriteController" für Schreibzugriffe an der REST-Schnittstelle
[plantuml,VideospielGetController,svg]
----
include::VideospielWriteController.plantuml[]
----

=== Die GraphQL-Schnittstelle

GraphQL ermöglicht eine zustandslose Abfrage. Der QueryResolver nimmt 
Requests entgegen für Suchen.

.VideospielQueryResolver für Lesezugriffe an der GraphQL-Schnittstelle
[plantuml,VideospielQueryResolver,svg]
----
include::VideospielQueryResolver.plantuml[]
----

Der MutationResolver nimmt Requests entgegen für Schreiben.

.VideospielMutationResolver für Schreibzugriffe an der GraphQL-Schnittstelle
[plantuml,VideospielMutationResolver,svg]
----
include::VideospielMutationResolver.plantuml[]
----

=== Der Anwendungskern

Gehört zum Anwendungskern und verarbeitet Suchanfragen.

."VideospielReadService" im Anwendungskern
[plantuml,VideospielReadService,svg]
----
include::VideospielReadService.plantuml[]
----

Gehört zum Anwendungskern und verarbeitet Schreibanfragen.

."VideospielWriteService" im Anwendungskern
[plantuml,VideospielWriteService,svg]
----
include::VideospielWriteService.plantuml[]
----

=== Klasse für Entities

Die Entity Videospiel, als Aggregate Root.

.Entity
[plantuml,Videospiel,svg]
----
include::Videospiel.plantuml[]
----

== Programmierrichtlinien für TypeScript und JavaScript

Für die Programmierung mit *TypeScript* und *JavaScript* wird folgende
Styleguides empfehlenswert:

[horizontal]
_Microsoft_:: https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines
_Angular_:: https://angular.io/docs/ts/latest/guide/style-guide.html
_Google_:: https://google.github.io/styleguide/tsguide.html
_React_:: https://github.com/airbnb/javascript/tree/master/react
