#  "." am Anfang bezeichnet den Top-Level Namensraum

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.phpMyAdmin.name }}
data:
  TZ: Europe/Berlin
  LANG: de_DE.utf8
  PMA_HOST: {{ include "mysql.fullname" . }}
  PMA_PORT: "3306"
  PMA_ARBITRARY: "1"
