#  "." am Anfang bezeichnet den Top-Level Namensraum

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.phpMyAdmin.name }}
  labels:
    {{- include "phpMyAdmin.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "phpMyAdmin.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      name: {{ .Values.phpMyAdmin.name }}-svc
      targetPort: {{ .Values.phpMyAdmin.name }}
