# Aufruf:   helmfile apply
#               zzgl. Port-Forwarding fuer phpMyAdmin durch port-forward.ps1
#           helmfile destroy

releases:
  - name: mysql
    namespace: acme
    chart: mysql
    values: [mysql/dev.yaml]
    wait: true
