# Aufruf:   i.a. bereits eingestellt:   $env:SKAFFOLD_PROFILE = 'dev'
#           skaffold dev
#           skaffold delete

apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: mysql
deploy:
  helm:
    releases:
      - name: mysql
        chartPath: mysql
        valuesFiles: [mysql/values.yaml]
        namespace: acme
profiles:
  - name: dev
    activation:
      - env: SKAFFOLD_PROFILE=dev
    deploy:
      helm:
        releases:
          - name: mysql
            chartPath: mysql
            valuesFiles: [mysql/values.yaml, mysql/dev.yaml]
            namespace: acme
    portForward:
      - resourceType: service
        resourceName: mysql
        port: mysql-svc
        localPort: 3306
      - resourceType: service
        resourceName: phpmyadmin
        port: phpmyadmin-svc
        localPort: 8889
