# "." am Anfang bezeichnet den Top-Level Namensraum bei Helm

apiVersion: v1
# https://kubernetes.io/docs/concepts/configuration/configmap
kind: ConfigMap
metadata:
  name: {{ include "buch.fullname" . }}
data:
  TZ: Europe/Berlin
  NODE_ENV: {{ .Values.nodeConfig }}
  LOG_DIR: /var/log/node
  LOG_LEVEL: {{ .Values.loglevel }}
  # String "true" statt Boolean true durch die Funktion quote
  LOG_PRETTY: {{ quote .Values.logPretty }}
  #APOLLO_DEBUG: "false"
  HEALTH_PRETTY_PRINT: {{ quote .Values.logHealthyPretty }}
  DB_HOST: postgres
  DB_USER: {{ .Values.dbUser }}
  DB_PASS: {{ .Values.dbPassword }}
  DB_POPULATE: {{ quote .Values.dbPopulate }}
  K8S_TLS: 'false'
  USER_PASSWORD_ENCODED: {{ .Values.userPasswordEncoded }}
