# https://kubernetes.io/docs/concepts/services-networking/network-policies
# https://hub.armosec.io/docs/c-0054
# https://hub.armosec.io/docs/c-0049

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "buch.fullname" . }}
spec:
  # Spezifikation, auf welche Pods die NetworkPolicy angewendet wird
  podSelector:
    matchLabels: {{- include "buch.selectorLabels" . | nindent 6 }}
  policyTypes: [Ingress, Egress]
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: postgres
              app.kubernetes.io/name: postgres
              app.kubernetes.io/instance: postgres
      ports:
        - port: 5432
          protocol: TCP
  ingress: []
