apiVersion: v1
# https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account
kind: ServiceAccount
metadata:
  name: {{ include "videospiel.fullname" . }}
  labels:
    account: {{ include "videospiel.fullname" . }}
automountServiceAccountToken: false
