# disruption = Störung

apiVersion: policy/v1
# https://kubernetes.io/docs/tasks/run-application/configure-pdb
kind: PodDisruptionBudget
metadata:
  name: {{ include "videospiel.fullname" . }}
  labels: {{- include "videospiel.labels" . | nindent 4 }}
spec:
  # minAvailable: 1
  maxUnavailable: 1
  selector:
    matchLabels: {{- include "videospiel.selectorLabels" . | nindent 6 }}
