# "." am Anfang bezeichnet den Top-Level Namensraum bei Helm

apiVersion: v1
# https://kubernetes.io/docs/concepts/configuration/configmap
kind: ConfigMap
metadata:
  name: {{ include "mailserver.fullname" . }}
data:
  # Key-Value-Paare (hier: fuer die Umgebungsvariable)
  TZ: Europe/Berlin
  SPRING_OUTPUT_ANSI_ENABLED: {{ .Values.outputAnsiEnabled }}
  SPRING_MAIN_BANNER-MODE: {{ .Values.bannerMode }}
  SPRING_LAZY-INITIALIZATION: "true"
  SPRING_JPA_OPEN-IN-VIEW: "true"
