# https://kubernetes.io/docs/concepts/services-networking/network-policies
# https://hub.armosec.io/docs/c-0054
# https://hub.armosec.io/docs/c-0049

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mailserver.fullname" . }}
spec:
  # Spezifikation, auf welche Pods die NetworkPolicy angewendet wird
  podSelector:
    matchLabels:
      {{- include "mailserver.selectorLabels" . | nindent 6 }}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: buch
              app.kubernetes.io/name: buch
              app.kubernetes.io/instance: buch
      ports:
        - port: smtp
          protocol: TCP
  egress: []
