#  "." am Anfang bezeichnet den Top-Level Namensraum

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.pgadmin.name }}
  labels:
    account: {{ .Values.pgadmin.name }}
automountServiceAccountToken: false
