#  "." am Anfang bezeichnet den Top-Level Namensraum

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mysql.name" . }}-db-volume
  labels:
    app.kubernetes.io/name: {{ include "mysql.name" . }}-db
    app.kubernetes.io/instance: {{ include "mysql.name" . }}-db
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: datenbank
    app.kubernetes.io/part-of: acme
    helm.sh/chart: {{ include "mysql.chart" . }}
spec:
  capacity:
    storage: 2Gi
  accessModes: [ReadWriteOnce]
  storageClassName: manual
  hostPath:
    path: /run/desktop/mnt/host/c/Zimmermann/volumes/mysql/db
    type: Directory

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mysql.name" . }}-tmp-volume
  labels:
    app.kubernetes.io/name: {{ include "mysql.name" . }}-tmp
    app.kubernetes.io/instance: {{ include "mysql.name" . }}-tmp
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: datenbank
    app.kubernetes.io/part-of: acme
    helm.sh/chart: {{ include "mysql.chart" . }}
spec:
  capacity:
    storage: 128Ki
  accessModes: [ReadWriteOnce]
  storageClassName: manual
  hostPath:
    path: /run/desktop/mnt/host/c/Zimmermann/volumes/mysql/tmp
    type: Directory

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mysql.name" . }}-mysqld-volume
  labels:
    app.kubernetes.io/name: {{ include "mysql.name" . }}-mysqld
    app.kubernetes.io/instance: {{ include "mysql.name" . }}-mysqld
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: datenbank
    app.kubernetes.io/part-of: acme
    helm.sh/chart: {{ include "mysql.chart" . }}
spec:
  capacity:
    storage: 256Ki
  accessModes: [ReadWriteOnce]
  storageClassName: manual
  hostPath:
    path: /run/desktop/mnt/host/c/Zimmermann/volumes/mysql/mysqld
    type: Directory
