# disruption = Störung

apiVersion: policy/v1
# https://kubernetes.io/docs/tasks/run-application/configure-pdb
kind: PodDisruptionBudget
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  # minAvailable: 1
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "mysql.selectorLabels" . | nindent 6 }}
