apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}
  ports:
    - port: 3306
      name: {{ include "mysql.name" . }}-svc
      targetPort: {{ include "mysql.name" . }}
